version: "3"
services:
  app:
    # build = dockerイメージをビルドする時の設定
    build:
      context: .
      dockerfile: "Dockerfile"
    container_name: ho_ren_so_app
    # command = コンテナ起動時にコンテナ内で実行するコマンド（railsのサービスなのでrailsの起動コマンドを実行）
    # command: bash -c "rm -f tmp/pids/server.pid && ./bin/dev"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    # volumes = コンテナ内で発生したデータをコンテナの外部に永続化させるための設定（volumesは保存する箱みたいなもの）
    volumes:
      - .:/myproject
    # ports = ホストPCのポート：コンテナポート（コンテナの3000ポートをホストPCの3000ポートにバインディング（繋げるみたいな意味）する。）
    ports:
      - "3000:3000"
    # depends_on = dbサービス（コンテナ）を起動した後にappサービス(コンテナ)を起動する（依存関係のこと）
    depends_on:
      - db
      - chrome
    environment:
      SELENIUM_REMOTE_URL: http://chrome:4444/wd/hub
    # (stdin_open,tty) = コンテナ内でデバックできるようにする
    stdin_open: true
    tty: true
  db:
    image: postgres
    container_name: ho_ren_so_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: ho_ren_so_test_db
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql
    restart: always
  chrome:
    image: selenium/standalone-chrome:latest
    ports:
      - 4444:4444
volumes:
  postgres-data:
