version: "3"
services:
  app:
    # build = dockerイメージをビルドする時の設定
    build:
      context: .
      dockerfile: "Dockerfile"
    container_name: ho_ren_so_app
    # command = コンテナ起動時にコンテナ内で実行するコマンド（railsのサービスなのでrailsの起動コマンドを実行）
    # command: bash -c "rm -f tmp/pids/server.pid && ./bin/dev"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    # volumes = コンテナ内で発生したデータをコンテナの外部に永続化させるための設定（volumesは保存する箱みたいなもの）
    volumes:
      - .:/myproject
    # ports = ホストPCのポート：コンテナポート（コンテナの3000ポートをホストPCの3000ポートにバインディング（繋げるみたいな意味）する。）
    ports:
      - "3000:3000"
      - "3035:3035"
    # depends_on = dbサービス（コンテナ）を起動した後にappサービス(コンテナ)を起動する（依存関係のこと）
    depends_on:
      - db
      - chrome
      - redis
    environment:
      SELENIUM_REMOTE_URL: http://chrome:4444/wd/hub
      REDIS_URL: redis://redis:6379/0
    # (stdin_open,tty) = コンテナ内でデバックできるようにする
    stdin_open: true
    tty: true
  db:
    image: postgres
    container_name: ho_ren_so_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: ho_ren_so_test_db
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql
    restart: always
  chrome:
    image: selenium/standalone-chrome:latest
    ports:
      - 4444:4444
  redis:
    # (image: redis) = db:と環境を統一して常に最新バージョンを使用
    # (image: redis:6.2) = db:と統一ぜず安定バージョンに固定する際はこの記述へ要変更
    image: redis
    container_name: ho_ren_so_redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    # (restart: always) = コンテナ停止時に自動で再起動するためのオプション
    restart: always
volumes:
  postgres-data:
  redis-data:
